import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { Logger } from 'winston';

export interface KnowledgeEntry {
  readonly pattern: string;
  readonly lesson: string;
  readonly timestamp: string;
}

const KNOWLEDGE_HEADER = `# QA Agent Knowledge Base

> Auto-accumulated learnings from test failures. Referenced in all future QA calls.

`;

export async function readKnowledge(knowledgePath: string): Promise<string> {
  try {
    const content = await readFile(knowledgePath, 'utf-8');
    return content;
  } catch {
    return '';
  }
}

export async function appendKnowledge(
  knowledgePath: string,
  entries: readonly KnowledgeEntry[],
  logger: Logger,
): Promise<void> {
  if (entries.length === 0) return;

  const existing = await readKnowledge(knowledgePath);
  const existingLower = existing.toLowerCase();

  // Deduplicate — skip entries whose lesson is already present
  const newEntries = entries.filter(
    (e) => !existingLower.includes(e.lesson.toLowerCase().substring(0, 60)),
  );

  if (newEntries.length === 0) {
    logger.debug('[qa-knowledge] No new knowledge to append (all duplicates)');
    return;
  }

  const base = existing.length > 0 ? existing : KNOWLEDGE_HEADER;
  const additions = newEntries
    .map((e) => `## ${e.pattern}\n\n${e.lesson}\n\n_Recorded: ${e.timestamp}_\n`)
    .join('\n');

  await mkdir(dirname(knowledgePath), { recursive: true });
  await writeFile(knowledgePath, `${base}\n${additions}`, 'utf-8');

  for (const entry of newEntries) {
    logger.info(`[qa-knowledge] Added: "${entry.pattern}"`);
  }
}

export function analyzeTestErrors(testOutput: string): readonly KnowledgeEntry[] {
  const entries: KnowledgeEntry[] = [];
  const timestamp = new Date().toISOString();

  // Pattern: import resolution failures — wrong relative path from tests/ to code/
  if (testOutput.includes(`Cannot find module`)) {
    const moduleRegex = /Cannot find module '([^']+)'/g;
    let moduleMatch: RegExpExecArray | null;

    // Extract the source file that triggered the import failure
    const sourceFileMatch = /at\s+(?:\S+\s+\()?([^\s)]+\.m?ts)/.exec(testOutput);
    const sourceFile = sourceFileMatch?.[1] ?? `unknown source file`;

    while ((moduleMatch = moduleRegex.exec(testOutput)) !== null) {
      const badPath = moduleMatch[1] ?? `unknown`;

      if (!badPath.includes(`/code/`) && !badPath.includes(`\\code\\`)) {
        entries.push({
          pattern: `Import resolution: tests must import from ../code/`,
          lesson: [
            `Test files live in \`tests/\` and source code lives in \`code/\`.`,
            `Imports from test files to source code MUST use the \`../code/\` prefix.`,
            `Example: \`import { foo } from '../code/src/utils/foo.mts';\``,
            `BAD: \`import { foo } from '../src/utils/foo.mts';\` — this skips the code/ directory.`,
            `Failed import that triggered this: \`${badPath}\``,
          ].join(`\n`),
          timestamp,
        });
      }

      // Enhanced: identify the source file and missing module for codegen feedback
      entries.push({
        pattern: `Cannot find module: ${badPath}`,
        lesson: [
          `File \`${sourceFile}\` tried to import \`${badPath}\` but it does not exist.`,
          `Either generate the missing file at the expected path, or fix the import path in \`${sourceFile}\`.`,
          `Common causes:`,
          `- The file was never generated by codegen`,
          `- The relative path is wrong (wrong number of \`../\` segments)`,
          `- The file extension is missing or incorrect (must be \`.mts\`)`,
        ].join(`\n`),
        timestamp,
      });
    }
  }

  // Pattern: module not found (package not installed in workspace)
  if (testOutput.includes('ModuleNotFound') || testOutput.includes('Cannot find package')) {
    const pkgMatch = /Cannot find package '([^']+)'/.exec(testOutput);
    const pkg = pkgMatch?.[1] ?? 'unknown';

    entries.push({
      pattern: 'Missing package in test workspace',
      lesson: [
        `Tests run in an isolated workspace directory that has no node_modules.`,
        `Do NOT import third-party packages unless they are available in the workspace.`,
        `Prefer testing with built-in bun:test utilities and inline mocks.`,
        `Missing package that triggered this: \`${pkg}\``,
      ].join('\n'),
      timestamp,
    });
  }

  // Pattern: bun test filter mismatch
  if (testOutput.includes('filters did not match any test files')) {
    entries.push({
      pattern: 'Bun test filter path mismatch',
      lesson: [
        `The \`bun test <filter>\` argument is matched relative to --cwd.`,
        `Always pass a path relative to the task root directory, e.g. \`tests/my.test.mts\`.`,
        `Never pass an absolute or project-root-relative path as the filter.`,
      ].join('\n'),
      timestamp,
    });
  }

  // Pattern: SyntaxError in generated test
  if (testOutput.includes('SyntaxError')) {
    const syntaxMatch = /SyntaxError:\s*(.+)/.exec(testOutput);
    const detail = syntaxMatch?.[1] ?? 'unknown syntax error';

    entries.push({
      pattern: 'SyntaxError in generated test file',
      lesson: [
        `Generated test file had a syntax error: ${detail}`,
        `Ensure all generated TypeScript is valid. Common issues:`,
        `- Missing closing braces or parentheses`,
        `- Using non-existent imports from the source code`,
        `- Mixing CommonJS and ESM syntax`,
      ].join('\n'),
      timestamp,
    });
  }

  // Pattern: import type erased at runtime — causes ReferenceError
  if (testOutput.includes(`is not defined`)) {
    const refMatch = /ReferenceError:\s*(\w+)\s+is not defined/.exec(testOutput);
    const name = refMatch?.[1] ?? `unknown`;

    entries.push({
      pattern: `ReferenceError: runtime value not defined (likely import type)`,
      lesson: [
        `\`${name}\` is not defined at runtime.`,
        `This usually means the code uses \`import type { ${name} }\` instead of \`import { ${name} }\`.`,
        `\`import type\` is erased at runtime by TypeScript — the value no longer exists.`,
        `Fix: change \`import type { ${name} }\` to \`import { ${name} }\` in the source code.`,
        `RULE: Never use \`import type\` for values that are used at runtime (constructors, functions, classes).`,
      ].join(`\n`),
      timestamp,
    });
  }

  // Pattern: non-JSON response from endpoint — likely missing .onError() or wrong content type
  if (testOutput.includes(`Failed to parse JSON`) || testOutput.includes(`is not valid JSON`)) {
    entries.push({
      pattern: `Endpoint returning non-JSON response`,
      lesson: [
        `One or more endpoints returned a non-JSON response body.`,
        `ALL endpoints MUST return valid JSON with Content-Type: application/json.`,
        `Common causes:`,
        `- Missing \`.onError()\` handler on the Elysia app — unhandled errors return HTML`,
        `- Route handler returning a raw string instead of an object`,
        `- 404 fallback not configured — Elysia default 404 is plain text "NOT_FOUND"`,
        `Fix: add \`.onError()\` to return JSON errors, and ensure all route handlers return objects.`,
      ].join(`\n`),
      timestamp,
    });
  }

  // Pattern: async/sync mismatch — Promise leaked as response body
  if (testOutput.includes(`[object Promise]`)) {
    entries.push({
      pattern: `Promise object leaked as response body`,
      lesson: [
        `A route handler returned a Promise object instead of the resolved value.`,
        `This means the handler is missing \`async\`/\`await\`.`,
        `Fix: make the route handler \`async\` and \`await\` all service/repository calls.`,
        `Example: \`app.get('/users', async () => { const users = await userService.getAll(); return { data: users }; })\``,
      ].join(`\n`),
      timestamp,
    });
  }

  // Pattern: native addon load failure or unsupported Bun module
  if (testOutput.includes(`ERR_DLOPEN_FAILED`) || testOutput.includes(`is not yet supported in Bun`)) {
    const dlopenMatch = /Cannot (?:load|open) (?:native addon|shared library)[^:]*:\s*(.+)/.exec(testOutput);
    const unsupportedMatch = /"([^"]+)" is not yet supported in Bun/.exec(testOutput);
    const detail = unsupportedMatch?.[1] ?? dlopenMatch?.[1] ?? `unknown native module`;

    entries.push({
      pattern: `Native addon or unsupported module failure`,
      lesson: [
        `A native Node.js addon failed to load: ${detail}`,
        `Bun does not support all native addons. Use Bun-native alternatives instead:`,
        `- Database: Use \`bun:sqlite\` (built-in) — NOT \`better-sqlite3\`, \`sqlite3\`, or any npm SQLite package`,
        `- Password hashing: Use \`Bun.password.hash()\` and \`Bun.password.verify()\` — NOT \`bcrypt\` or \`argon2\``,
        `- JWT: Use \`jose\` (pure JS) — NOT \`jsonwebtoken\``,
        `These Bun-native APIs require no npm install and avoid native compilation issues.`,
      ].join(`\n`),
      timestamp,
    });
  }

  // Pattern: type errors from wrong exports
  if (testOutput.includes(`is not a function`) || testOutput.includes(`is not exported`)) {
    entries.push({
      pattern: 'Incorrect export assumptions in tests',
      lesson: [
        `Tests assumed exports that don't exist in the source code.`,
        `Only import functions, classes, and types that are actually exported by the code files.`,
        `Review the code files provided and only use exports that are explicitly declared.`,
      ].join('\n'),
      timestamp,
    });
  }

  return entries;
}
