export function createCodegenUserPrompt(
  taskName: string,
  taskDescription: string,
  existingCode?: string,
): string {
  let prompt = `## Task: ${taskName}

${taskDescription}`;

  if (existingCode) {
    prompt += `

## Existing Code Context
The following code has already been generated by previous tasks. You can import from these modules:
${existingCode}`;
  }

  prompt += `

Generate all required files with complete implementations. Use fenced code blocks with file paths.`;

  return prompt;
}
