export function createFixPrompt(
  taskName: string,
  taskDescription: string,
  previousCode: string,
  errors: readonly string[],
  taskType?: string,
  existingCode?: string,
  taskId?: string,
): string {
  // Extract file paths from "// path" comment headers in previousCode
  const pathPattern = /^\/\/\s+(src\/[^\n]+\.mts|[^\n]+\.mts)/gm;
  const paths: string[] = [];
  let pathMatch: RegExpExecArray | null;
  while ((pathMatch = pathPattern.exec(previousCode)) !== null) {
    const p = pathMatch[1]?.trim();
    if (p) paths.push(p);
  }

  const pathListing = paths.length > 0
    ? `## Expected File Paths (use EXACTLY these — do NOT add extra \`src/\` prefixes)\n${paths.map((p) => `- \`${p}\``).join('\n')}\n\n`
    : ``;

  const typeInstruction = taskType && taskType !== `setup`
    ? `\n**IMPORTANT**: This is NOT a setup task (type: ${taskType}). Do NOT generate src/index.mts. Only setup tasks create the Elysia app entry file.${taskType === `endpoint` ? ` Endpoint tasks export Elysia plugins — do NOT call .listen().` : ``}\n`
    : ``;

  const dependencySection = existingCode
    ? `\n## Available Code from Dependencies (DO NOT RECREATE — IMPORT THESE)
The following code was generated by completed dependency tasks. You MUST import types, utilities, and modules from these files instead of recreating them.
Do NOT duplicate any types, interfaces, or utilities shown below — doing so causes module conflicts.

${existingCode}
`
    : ``;

  return `## Task: ${taskName}${taskType ? `\nTask type: ${taskType}` : ``}

${taskDescription}
${typeInstruction}${dependencySection}
## Previous Code (has errors)
${previousCode}

${pathListing}## Errors to Fix
${errors.map((e, i) => `${i + 1}. ${e}`).join('\n')}

**IMPORTANT**: Do NOT modify code that is already working. Only fix the specific errors listed below.

Fix ALL the errors above. Output the complete corrected files using fenced code blocks with file paths.
Do not skip any files — regenerate all files for this task with the fixes applied.

**IMPORTANT**: Use the EXACT same file paths as shown above (e.g. \`src/index.mts\`, NOT \`src/src/index.mts\`). Do NOT add extra \`src/\` prefixes.
Also regenerate the test file as \`tests/${taskId ?? `task`}.test.mts\` with fixes applied. The test MUST only import names you actually exported.`;
}
