const CODEGEN_TEST_INSTRUCTIONS: Readonly<Record<string, string>> = {
  setup: await Bun.file(`${import.meta.dir}/md/codegen-tests/setup.md`).text(),
  model: await Bun.file(`${import.meta.dir}/md/codegen-tests/model.md`).text(),
  repository: await Bun.file(`${import.meta.dir}/md/codegen-tests/repository.md`).text(),
  service: await Bun.file(`${import.meta.dir}/md/codegen-tests/service.md`).text(),
  endpoint: await Bun.file(`${import.meta.dir}/md/codegen-tests/endpoint.md`).text(),
  middleware: await Bun.file(`${import.meta.dir}/md/codegen-tests/middleware.md`).text(),
};

function getTaskTypeTestInstructions(taskType?: string): string {
  return CODEGEN_TEST_INSTRUCTIONS[taskType ?? ``] ?? ``;
}

export function createCodegenUserPrompt(
  taskName: string,
  taskDescription: string,
  existingCode?: string,
  taskType?: string,
  taskId?: string,
): string {
  let prompt = `## Task: ${taskName}`;

  if (taskType) {
    prompt += `\nTask type: ${taskType}`;
  }

  if (taskId) {
    prompt += `\nTask ID: ${taskId} (use this for the test file path: \`tests/${taskId}.test.mts\`)`;
  }

  prompt += `\n\n${taskDescription}`;

  if (taskType && taskType !== `setup`) {
    prompt += `\n\n**IMPORTANT**: This is NOT a setup task. Do NOT generate src/index.mts. Only setup tasks create the Elysia app entry file.`;
  }

  if (taskType === `endpoint`) {
    prompt += `\nEndpoint tasks export Elysia plugins (e.g. \`export const fooRoutes = new Elysia({ prefix: '/api/v1/foo' })...\`). Do NOT call .listen() or create a standalone app.`;
  }

  if (existingCode) {
    prompt += `\n\n## Available Code from Dependencies (DO NOT RECREATE — IMPORT THESE)
The following code was generated by completed dependency tasks. You MUST import types, utilities, and modules from these files instead of recreating them.
For example, if you see \`Result<T, E>\` defined in \`src/types/result.mts\`, import it: \`import { Result } from '../types/result.mts'\`
Do NOT duplicate any types, interfaces, or utilities shown below — doing so causes module conflicts.

${existingCode}`;
  }

  prompt += getTaskTypeTestInstructions(taskType);

  prompt += `\n\nGenerate all required files with complete implementations. Use fenced code blocks with file paths.
Also generate the test file as \`tests/${taskId ?? `task`}.test.mts\`. The test MUST only import names you actually exported.`;

  return prompt;
}
